version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saboro
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s 
      timeout: 5s  
      retries: 5    

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: saboro

    depends_on:
      db:
        condition: service_healthy # 

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data: